{
    "name":"Academic Information System v1.0",
    "version":"1.0",
    "depends": ["base","board"],
    "author":"your name",
    "category":"Education",
    "website":"your.website.com",
    "description":"""long description about your moduels""",

    "data":[
        "security/groups.xml",
        "security/ir.model.access.csv",
        "menu.xml",
        "course.xml",
        "session.xml",
        "attendee.xml",
        "partner.xml",
        "wizard/create_attendee.xml",
        "reports/session.xml",
        "dashboard.xml",
    ],
    "installabe":True,
    "auto_install":False,
    "application":True,
}